### ISSUE TITLE
Optimize User Stub / Missing PHPDocs

### ISSUE THREAD

**Issue by bihlmaierh** [Pseudoagentur/soa-sentinel#100]
Within the current user stub in development the edit and create method is not necessary. We can use the createAndEdit method and check, if id is null or not. So the code is better to read and to maintain.

In additon within the `SleepingOwl\Admin\FormItems\FormItem` - Class the PHPDoc for the new method `roles` and `permission` is missing so not autocomplete is possible.

Please correct this.

**Comment by bihlmaierh** [comment]
PHPDoc for chose is wrong too.

**Comment by noxify** [comment]
Stub updated

**Comment by noxify** [comment]
fixed
