### ISSUE TITLE
Role and User Permissions: Missing Scope

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#101]
Within the permission form item the functionallity for scope is missing.

It should be possible, to make a difference between frontend and backend permissions or other differences.

Please add this. Thanks.

**Comment by noxify** [comment]
Added new option `grouped()` to the permission form field.

http://docs.pseudoagentur.de/soa-sentinel/develop/field/permissions#grouped-permissions
