### ISSUE TITLE
Menu Handling with permissions

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#102]
Currently we have the problem, that the parent menu entry is shown, also if the child entries are not visible.

We have to find a solution, which will hide the parent menu entry even if there are no child entries.

**Comment by bihlmaierh** [comment]
Which release ?

**Comment by bihlmaierh** [comment]
@noxify Status ?

**Comment by noxify** [comment]
I have checked the Package https://github.com/caffeinated/menus 

It has some nice features like filtering, which helps us to show only the allowed links.
But maybe we can extract this functionality in our existing implementation, which is currently a better solution, because if we're using another menu package, each of us has to rebuild/redefine the menus in all projects.

**Comment by bihlmaierh** [comment]
Addional Information:

All menue points are shown. Role will be ignored.

**Comment by johnshepherd** [comment]
Any thoughts on a solution for this, even if temporary? It's a bit of a blocker for me at the moment. Happy to contribute with code but don't want to step on any toes if there are already plans.

**Comment by noxify** [comment]
Hi,

currently I had not the time to continue on this issue.
I will try to find some time to implement the new menu logic based on caffeinated/menus.

Sorry!

**Comment by noxify** [comment]
Found a solution without changing the menu handling at all.

With this fix, the menu permissions from each children will be added to the parent.

This solves our problem.

Added it to the 3.0.2 milestone, so it's available in the next release.
