### ISSUE TITLE
Admin Theme proposal

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#111]
To move adminTheme.config (basically remove)
And add a frontend page (js cookies) to manipulate the theme?
like color and etc. so each user can define his own style of admin:lte

**Comment by noxify** [comment]
sounds good.

Alternative idea:
We're using a "meta" field, which includes the config for the themes.

Example:
```
{
	"admin"	: {

		"theme"	: {
			'skin'				: 'blue',
			'fixed_layout'		: true,
		 	'boxed_layout' 		: false,
		 	'sidebar_mini'		: true,
		  	'toggle_sidebar'	: true,
		   	'sidebar_on_hover'	: true   
		}

	}
}
```

If nothing is defined (e.g. field = null) then we will use the fallback value from the config.

Maybe we can then also save the values from the datatables (changed sortorder etc.) also in the meta field.

Also the field can be used to define dashboard widgets or so..

Ideas over ideas :)

**Comment by noxify** [comment]
I have added the possibility to change the theme options per user.

Now the user can change the theme settings via the "user settings" and in the user management you can change the theme setting for each user.

In the "user settings" is also a button to reset the theme settings to the default settings from the theme config (admintheme.php).

I have to run some tests, if everything works fine, i will close this issue.

**Comment by noxify** [comment]
Fixed a bug, which prompts a error page in case that the user is not logged in.

Now everything works as expected.

After you run a `composer update` for the `develop` branch.
You also have to run `php artisan vendor:publish` and `php artisan migrate`.

**Comment by noxify** [comment]
Please check also the new stubs:

* menu: https://github.com/Pseudoagentur/soa-sentinel/blob/develop/src/SleepingOwl/Admin/Commands/stubs/menu.stub

* User: https://github.com/Pseudoagentur/soa-sentinel/blob/develop/src/SleepingOwl/Admin/Commands/stubs/User.stub
