### ISSUE TITLE
Creating of User throws "Integrity constraint violation"

### ISSUE THREAD

**Issue by bihlmaierh** [Pseudoagentur/soa-sentinel#117]
Hi @noxify ,

with a new environment I get the following error:

`Illuminate \ Database \ QueryException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `role_users` (`created_at`, `role_id`, `updated_at`, `user_id`) values (2015-11-10 07:42:00, 1, 2015-11-10 07:42:00, )) `

Verwendetes Model: 
http://laravel.io/bin/zjvnJ

Can u fix this ?

Thanks!

**Comment by bihlmaierh** [comment]
@noxify 
Status ? This is a blocker.

**Comment by noxify** [comment]
Checked it with a fresh installation.

Everything is working fine. Tested with the default Admin User Model and also with your Admin Model.
