### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#121]
In 3.0.1 If youd dont use ajax validation, doesnt show errors in help-block, just input becames red without error message.

**Comment by Froxz** [comment]
Ok, I found why it is now showing,
```js
formItem/erros.blade.php
```
If I remove ```$prefix``` it works correctly..

**Comment by heikobihlmaier** [comment]
this is fixed in develop branch. please stay tuned for next release!
