### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#122]
if  sorting is applied to display, after clicking on another column sort is not working it possible to sort, on display by date and after use datatables sorting?
```php
$display->apply(function ($query){
      $query->orderBy('created_at', 'desc');
});
```

**Comment by heikobihlmaier** [comment]
I know no possibility for that because datatables sort table rows and not database results.

@noxify do you know something other ?

**Comment by noxify** [comment]
To order the result from the Datatables, you have to use something like this:

```
…->display(function ()
{
    $display = AdminDisplay::datatables();
    $display->order([[0, 'desc'], [2, 'asc']]);
    // configure display
    return $display;
})
```

Please check for detailed information our documentation page: http://docs.pseudoagentur.de/soa-sentinel/master/display/types#datatables

**Comment by Froxz** [comment]
@noxify Thank you missed that.

**Comment by noxify** [comment]
@Froxz - no problem :) 

have a nice sunday :)

**Comment by Froxz** [comment]
@noxify)))) u2)
