### ISSUE TITLE
Load dump records timeout.

### ISSUE THREAD

**Issue by peterdu88** [Pseudoagentur/soa-sentinel#128]
If there are more than 5000 record in the databases, the I create admin:model to list all of them, it seems timeout.

**Comment by Froxz** [comment]
for so many records is better to use DataTableasync()

**Comment by noxify** [comment]
Hi,

what kind of Display Table are you using?

If you're using `Display::table()` or `Display::datatable()` you will get all records directly.
Only `AdminDisplay::datatablesAsync()` can handled paging currently.

Maybe you can paste your Admin Model, then I can create locally some fake data to test something.

I have checked the datatables documentation and their are some options which are not active in our implementation.

Thanks a lot for reporting :)

Greets
Marcus

**Comment by peterdu88** [comment]
Thanks all. It is work.
