### ISSUE TITLE
Creating a publicly accessible route

### ISSUE THREAD

**Issue by johnshepherd** [Pseudoagentur/soa-sentinel#130]
With the addition of authorisation, is it possible to create a publicly accessible route? In particular, I'm thinking of a password reset page. I guess could change the defaultPermission in the config, but I don't really want to do that!

**Comment by noxify** [comment]
Hi,

if you create the reset page outside the admin context (e.g. app/Http/Controllers/ResetPasswordController.php) you should be able to create whatever you want without any limitation.

**Comment by noxify** [comment]
If you need a example or any kind of help, we will give our best to find a solution.

**Comment by heikobihlmaier** [comment]
Closed.

Feel free to reopen it, when you have additional questions.
