### ISSUE TITLE
Locale 3.0.2

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#132]
Does locale switching and middleware affects the whole "website" or only admin part? cz I have strange behavior on my site now. If I switch language in Admin it switches also on the site))) and now users cant change theori locale.
Middleware uses applocale session but is only on admin routes, how is possible?

**Comment by Froxz** [comment]
Ok fixed it by another middleware + prefix in RouteProvider

**Comment by noxify** [comment]
hi,

i didn't checked it in the frontend.
But if you found a solution, we can close this issue?

**Comment by Froxz** [comment]
yeap thank you
