### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#133]
Check support for Laravel 5.2

**Comment by noxify** [comment]
Tested with
* PHP 7
* mySQL 5.5.42
* Laravel 5.2.5
* develop branch

Currently, it looks like, that it is working without problems.
All our dependencies have updated their dependencies, so it's possible to install the admin package with the latest laravel version.

**Comment by noxify** [comment]
There were some problems.
Fixed some but have to test oob functionality.
