### ISSUE TITLE
Bug in AdminServiceProvider: Default Laravel Language always go to fallback language

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#135]
The following condition within the AdminServiceProvider breaks the default language of laravel and throws always to fallback language:

     if (\Config::get('admin.language_switcher') && \Session::has('applocale') &&   array_key_exists(\Session::get('applocale'), \Config::get('admin.languages'))) {
            \App::setLocale(\Session::get('applocale'));
        }
        else { // This is optional as Laravel will automatically set the fallback language if there is none specified
            \App::setLocale(\Config::get('app.fallback_locale'));
        }

STPs:
1.) laravel locale to "de", fallback locale to "en"
2.) admin.language_switcher to false
3.) remove language middleware from admin config

Please fix this, thanks.

**Comment by noxify** [comment]
fixed
