### ISSUE TITLE
Automatically Loading of requried Service Provider and Aliases

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#136]
To minimize the effort the the end user, we will cleanup the configuration.

Current Situation:
Even when we add a new package, the user has to change the `config/app.php`.

Future Situation:
The User has our AdminServiceProvider in the `config/app.php` and all required provider and aliases will be loaded via our AdminServiceProvider.

**Comment by noxify** [comment]
Updated documentation:
http://docs.pseudoagentur.de/soa-sentinel/develop/setup/installation#file-modifications

**Comment by heikobihlmaier** [comment]
Can u add the information that the necessarcy service provider and facades automatically loaded?

**Comment by noxify** [comment]
done: http://docs.pseudoagentur.de/soa-sentinel/develop/setup/installation#file-modifications
