### ISSUE TITLE
FormItem "Select": Deactivation of Sorting is not possible

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#138]
Code Example:

     FormItem::chosen('type', 'Typ')->options(['category' => 'Kategorie', 'faq-article' => 'Frage & Antwort'], false)->nullable(true)

This results in the order
1.) Frage & Antwort
2.) Kategorie

But I disabled sorting so it should be
1.) Kategorie
2.) Frage & Antwort

**Comment by heikobihlmaier** [comment]
I assigned me this bug, because I found the error.

Fix cooming soon.

**Comment by heikobihlmaier** [comment]
my fix doesn't work. @noxify can u look ? the error is here:

https://github.com/Pseudoagentur/soa-sentinel/blob/master/src/SleepingOwl/Admin/FormItems/Select.php#L168

When u have only an array with this call the sort param is overwritten.

I test it without the function call and include directly the protected array. this doesn't work with model options.

Can u look ?

**Comment by noxify** [comment]
yes i can

**Comment by noxify** [comment]
Fixed.

I have changed the functionality. 
Instead the second argument, you have now to use `->disableSort()`.

http://docs.pseudoagentur.de/soa-sentinel/develop/field/select#disable-sorting
