### ISSUE TITLE
Editor File Manager

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#14]
Implement File Manager for CKEditor and tinyMCE based on https://github.com/guillermomartinez/filemanager-laravel

**Comment by bihlmaierh** [comment]
File Manager installs tinymce plugin. So with this implentation issue #12 can be done in one step.

**Comment by bihlmaierh** [comment]
Package "bestmomo/filemanager"  is not necessary.

Package https://github.com/guillermomartinez/filemanager-laravel has a implentation of the same filemanager. TinyMCE Plugin is only a demo.

**Comment by bihlmaierh** [comment]
Change branch to "feature/Editor_Filemanager"

**Comment by bihlmaierh** [comment]
With #6 user can upload files to directory "upload/" can this be default filemanager directory ?

Idea: Instead of File / Image Upload we define a new field for example `FormItem::filemanager`.

This form item opens the filemanager and add the possibility to select directly from filemanager.

**Comment by bihlmaierh** [comment]
Hi @noxify 

with pull request #38 I add a new config parameter "filemanagerDirectory".

Can u use this as default start point for the filemanager ? When yes, this would be very nice, because the user can directly show his uploads in the filemanager.

**Comment by noxify** [comment]
@bihlmaierh - sure

**Comment by noxify** [comment]
merged - @bihlmaierh please test the develop branch that everything is working

**Comment by bihlmaierh** [comment]
Working Status ?

**Comment by noxify** [comment]
WIP :) currently I'm checking the current develop branch to be sure that we have an working state.

**Comment by noxify** [comment]
with https://github.com/barryvdh/laravel-elfinder the implementation is done.
Please check & merge @bihlmaierh

**Comment by noxify** [comment]
Documentation is already updated with the new required service provider

**Comment by noxify** [comment]
merged
