### ISSUE TITLE
Optimatizion: Active Menu Link Detection

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#146]
Active-Menu-Link detection doesn't work for links with more then one depth.

Example:
`product categories` has a sub model with link to `products`.
When I open the edit page from `products` the menu link `product_categories` isn't active.

**Comment by noxify** [comment]
Changed calculation for active link detection.
Now we will calculate it inside the `MenuItem`.

So you have to update the `public/default/scripts/base/admin.js` as you can see in the commit.

To keep the menu entry active, also when the child model is not in the menu you have to do the following:

```
<?php

//Main Model: App\Entities\Products
\Admin::model('App\Entities\Products')->title('Products')->display(function () {
    $display = AdminDisplay::table();

    //columns
    return $display;
})->createAndEdit(function ($id)
{
    $display = AdminDisplay::tabbed();
    $display->tabs(function () use ($id)
    {
        $tabs = [];

        $form = AdminForm::form();
        $form->items([
            FormItem::columns()->columns([
                //form items
            ]),
        ]);
        $tabs[] = AdminDisplay::tab($form)->label('Main Form')->active(true);

        if ( ! is_null($id))
        {
            $instance = App\Entities\Product::find($id);
 
            $attributes = Admin::model('App\Entities\ProductAttribute')->display();
            $attributes->scope('withAttribute', $id);
            $attributes->parameters(['product_id' => $id]);
            
            $tabs[] = AdminDisplay::tab($attributes)->label('Attributes)');
        }
        return $tabs;
    });
    return $display;
} );


//Sub Model: App\Entities\ProductAttributes
\Admin::model('App\Entities\ProductAttributes')->title('Attributes')->alias('products/attributes')->display(function () {
    $display = AdminDisplay::table();
    //attribute columns
    return $display;
})->createAndEdit(function ($id)
{
    $form = AdminForm::form();
    //attribute form
    return $form;
} );
```

In this example, the alias for the main model will be generated automatically and the result is `products`.
With the new active link detection, we're check the active link with 

```
\Request::is(config('admin.prefix').'/'.$this->alias().'/*')
```

With this solution, you should be able to set an menu entry active based on a sub model.
Only only have to ensure, that your `alias` for the submodel has the following structure:

```
->alias('<mainModelAlias>/<subModelName>')
```

**Comment by noxify** [comment]
Please test it and inform me about your test results.

I have tested it successfully with your given example.

**Comment by heikobihlmaier** [comment]
Successfully tested with two models.

Can u make the doc please ?

**Comment by noxify** [comment]
added: http://docs.pseudoagentur.de/soa-sentinel/develop/configuration/model#set-alias
