### ISSUE TITLE
[Feature Request] Custom Layout and Scripts

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#156]
Add the possibilty, that the user can add custom scripts and style files.

Good Ideas are a theming system or simple add all used css and scripts files as array to config.

**Comment by noxify** [comment]
Added.

It's now possible to define your custom styles and scripts inside the `app/Admin/bootstrap.php`.

Example:
```php
<? 
AssetManager::addStyle('admin::default/plugins/bootstrap/css/bootstrap22.min.css');

AssetManager::addScript('admin::default/plugins/bootstrap/css/bootstrap22.min.js');
```

**Comment by heikobihlmaier** [comment]
CSS and JS not working correctly, because the files are included before all other files.

So jquery cannot be found or all custom css settings are overwritten.

**Comment by noxify** [comment]
Added two new methods, which adds the assets at the end.

```
AssetManager::customStyle('admin::default/plugins/bootstrap/css/bootstrap22.min.css');
AssetManager::customScript('admin::default/plugins/bootstrap/css/bootstrap22.min.js');
```
