### ISSUE TITLE
[Bug] Laravel 5.2 and Sentinel Password

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#158]
See:
https://gist.github.com/heikobihlmaier/957b5ca5d177cee0e36f

**Comment by Froxz** [comment]
```php
if ( \Input::has($name) )
```
change to 
```php
$request->has($name)
```
Should work and also $request->merge()
Need to pass Closure to save(Request $request)

**Comment by heikobihlmaier** [comment]
No, we should call the facade.

That's all.

**Comment by Froxz** [comment]
@heikobihlmaier just proposal))

**Comment by heikobihlmaier** [comment]
Fix next morning ;)

**Comment by noxify** [comment]
fixed
