### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#161]
Hi, Sentiel permissions looks good but if you have a huge list, it is complicated to go through all this checkboxes maybe you should use something like this 
[Left-right myltiselect](http://crlcu.github.io/multiselect/#demo-zero-configuration)

**Comment by noxify** [comment]
Hmm... we had some plans to implement this as a Form item, but to use this to manage the permission makes no sense for me.

Maybe in the Roles definition but not in the User Definition.

Maybe we can create a search functionality within the permissions table.

We will discuss this internal.

I will close this - If you have any suggestions to this, feel free to reopen this issue.

**Comment by Froxz** [comment]
@noxify Basically I am thinking now how to avoid permission extra table, because first you have to create permission and after assign, if it is possible some bulk creation of permissions not 1 by 1

**Comment by noxify** [comment]
Hi,

i can't follow you - Can you explain it what you mean/want?

**Comment by Froxz** [comment]
@noxify When I Will get home, Will text you PM)))
