### ISSUE TITLE
AdminLTE Upgrade

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#17]
Upgrade to the latest version of AdminLTE

**Comment by noxify** [comment]
* New Assets implemented successfully
* Added new config file for the admin theme
* Updated Display Views

Need some tests to ensure that everything works fine.

**Comment by noxify** [comment]
@bihlmaierh - please check this PR with: 

`"pseudoagentur/soa-sentinel" : "dev-feature/AdminLTE_Upgrade",`

if everything works fine, we can push it to `develop`

**Comment by bihlmaierh** [comment]
Merged.
