### ISSUE TITLE
New Form Type: Bootstrap Wizard

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#19]
Add new form type to use Bootstrap Form Wizard http://vadimg.com/twitter-bootstrap-wizard-example/

**Comment by bihlmaierh** [comment]
Consideration: Create relationsships with bootstrap wizard eg 
first step -> customer 
second step  -> customer details

**Comment by bihlmaierh** [comment]
change milestone.

**Comment by heikobihlmaier** [comment]
I closed this.

Reason:
Bootstrap Wizard is currently not necessary. In addition the bootstrap wizard has problems with ajax validation. So when someone wants this, we can check it again.

-- CLOSE --
