### ISSUE TITLE
Class 'Debugbar' not found

### ISSUE THREAD

**Issue by Jok3r11of** [Pseudoagentur/soa-sentinel#28]
DebugBar is not found, had to install it.

**Comment by noxify** [comment]
master or develop branch?

**Comment by Jok3r11of** [comment]
master branch
```
FatalErrorException in BaseFormItem.php line 108:
Class 'Debugbar' not found
```

**Comment by noxify** [comment]
I have removed the Debugbar Statement.
Can you try it again?

**Comment by Jok3r11of** [comment]
Yes all good. Thank you

**Comment by noxify** [comment]
you're welcome. Thanks for reporting.
