### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#30]
I am trying to create a custom field e.g passowrd, where should I create view based on this doc : http://docs.pseudoagentur.de/soa_sentinel/form_fields#register-custom-field

**Comment by Jok3r11of** [comment]
sorry found in  /view/default/formitem Need to add to docs

**Comment by noxify** [comment]
yeah i saw this :) thanks for your feedback.

Path is: `/resources/views/vendor/admin-lte/default/formitem/`

**Comment by Jok3r11of** [comment]
Welcome, Thank you for great CRUD manager

**Comment by noxify** [comment]
Thanks :) But the most of the work did Sleeping-Owl.
We have forked his package and did some modifications (as you can see in the branch list :) )

**Comment by Jok3r11of** [comment]
@noxify 
I used for 4.2 but just started with L5, and only you suport  Sentinel

I opened it again because,
When password field is used, it store in mysql plaint text not hashed.

**Comment by noxify** [comment]
Yeah, currently the given admin model is not finished. I created it only to have it - sorry :(

What you can do as workaround is something like this:

```
FormItem::custom()->display(function ($instance)
		{
			//show password view based on the existing formfield
		    return view('admin-lte::default.formitem.password', ['name' => 'password','label' => 'Password','instance' => $instance])->render();
		})->callback(function ($instance)
		{
			//check that the password field is fileld
			if( !is_null( \Input::get('password') ) && !empty( \Input::get('password') ) ) {
		    	//use Hash::make to create a secure password hash
		    	//$instance->password = \Hash::make(\Input::get('password'));
		    	$instance->password = password_hash(\Input::get('password'));
			}

		})
```

`password_hash` comes from https://cartalyst.com/manual/sentinel/2.0#hashing

Maybe this solves your problem.

**Comment by Jok3r11of** [comment]
I see Sentinel uses 
```
$user = Sentinel::update($user, $credentials);
```
You solutions gives error
```
Undefined variable: label_size (View: /home/l2/laravel/vendor/pseudoagentur/soa-sentinel/src/views/default/formitem/password.blade.php)
```

I change it:
```
FormItem::password('password', 'Password')->required(),
```
And a setter in User model

```
public function setPasswordAttribute($pass){
	    $this->attributes['password'] = password_hash($pass, PASSWORD_BCRYPT);

	}
```

Also password_hash expects 2 parameters

**Comment by noxify** [comment]
Added in develop Branch:
* http://docs.pseudoagentur.de/soa-sentinel/develop/field/sentinelpassword
* http://docs.pseudoagentur.de/soa-sentinel/develop/field/password
