### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Jok3r11of** [Pseudoagentur/soa-sentinel#31]
It is possible to disable build in Login?

**Comment by bihlmaierh** [comment]
Hi @Jok3r11of,

currently it is not possible to disable build in login.

Why do you want disable the build in login ?

**Comment by Jok3r11of** [comment]
Because I want to add login for normal users with captcha and url without 'admin/login'

**Comment by bihlmaierh** [comment]
Hi @Jok3r11of,

I think, you can try to overwrite the SOA Middleware (https://github.com/Pseudoagentur/soa-sentinel/blob/master/src/SleepingOwl/Admin/Http/Middleware/AdminAuthenticate.php).

In this middleware we check, if user successfully authenticated.

Can u try this ?

**Comment by Jok3r11of** [comment]
@bihlmaierh 
I saw this, but cant understand why need to overwrite it?
Your middleware is good to check permissions.

**Comment by bihlmaierh** [comment]
Hi @Jok3r11of ,

you have 2 possibilities to implement your feature:

1. ) You have the login in frontend and check only in SOA, if user authenticated (middleware overwrite)
2.) You overwrite our layout files (change login layout) and overwrite the login controller.

Do you unterstand what I mean ?

**Comment by Jok3r11of** [comment]
@bihlmaierh Got that)))  THank you

**Comment by bihlmaierh** [comment]
Wunderful.

Feel free to give feedback.
