### ISSUE TITLE
columnFilters

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#34]
```
$display->columnFilters([
	    null, // first column has no column filter
	    ColumnFilter::text()->placeholder('Title'), // second column has text column filter
]);
```
Throws an error
```
Call to undefined method SleepingOwl\Admin\Display\DisplayTable::columnFilters()
```

**Comment by bihlmaierh** [comment]
Have u add `'ColumnFilter'  => 'SleepingOwl\Admin\ColumnFilters\ColumnFilter',` to  `config/app.php` ?

**Comment by bihlmaierh** [comment]
And please check

http://docs.pseudoagentur.de/soa_sentinel/display_filters

**Comment by Jok3r11of** [comment]
@bihlmaierh  aliases and providers are set.
I tried both ways:
```
'ColumnFilter'  => SleepingOwl\Admin\ColumnFilters\ColumnFilter::class,
'ColumnFilter'  => 'SleepingOwl\Admin\ColumnFilters\ColumnFilter',
```
I was doing everything how is shown in Docs

**Comment by bihlmaierh** [comment]
You need only on ColumnFilter entry.

Can u send me the complete model code ?

**Comment by Jok3r11of** [comment]
```
<?php

\Admin::model('App\Models\Settings')->title('Settings')->alias('settings')->permission("superadmin")->display(function ()
{
	$display = AdminDisplay::table();
	$display->columnFilters([
	    null, // first column has no column filter
	    ColumnFilter::text()->placeholder('Title'), // second column has text column filter
	]);
	$display->columns([
		Column::string('id')->label('#'),
		Column::string('key')->label('Key'),
		Column::string('value')->label('value'),
	]);
	return $display;
})->createAndEdit(function ()
{
	$form = AdminForm::form();
	$form->items([
		FormItem::columns()->columns([
			[
				FormItem::text('key', 'Key')->required('alpha_dash')->unique(),
			],
			[
				FormItem::text('value', 'Value')->required('alpha_dash'),
			],
		]),
	]);
	return $form;
});
```

**Comment by bihlmaierh** [comment]
We need to check this. This seems a general bug from orginal package.

Next week we can fix this. @noxify is currently in vacation.

Can u use datatables instead ?

**Comment by Jok3r11of** [comment]
Changed to 
$display = AdminDisplay::datatables(); or
$display = AdminDisplay::datatablesAsync();
And now this error

```
InvalidArgumentException in FileViewFinder.php line 112:
No hint path defined for [admin].
```

**Comment by bihlmaierh** [comment]
Remove the filter. Is error persistent ?

**Comment by Jok3r11of** [comment]
@bihlmaierh 
Nope without filter all good.

**Comment by bihlmaierh** [comment]
Great! We fix the error asap.

**Comment by Froxz** [comment]
Some update, I think that was my mistake, I saw the ```SleepingOwl\Admin\Display\Table```
 function ```columnFilters``` doesn't exist, but in ```SleepingOwl\Admin\DisplayDataTables``` exist,
So in order to use columnFilters I had to use ```AdminDisplay::datatables()``` instead of ```AdminDisplay::table()```
Correct this just in (Docs)[http://docs.pseudoagentur.de/soa_sentinel/display_types#table]

**Comment by noxify** [comment]
Thanks @Froxz for your feedback.

I will update the documentation

**Comment by noxify** [comment]
Documentation Updated: http://docs.pseudoagentur.de/soa_sentinel/display_types#datatables

If you found something else, feel free to open a new issue :)

Thanks!!

**Comment by Froxz** [comment]
@noxify Sure, thank you.
