### ISSUE TITLE
artisan PHP Catchable fatal error:

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#44]
Branch: Develop

when running artisan commands (or composer update + clear compiled)
```
PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/l2/laravel/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 64 and defined in /home/l2/laravel/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 99
```

The problems is in config/admin.php
```
'ckeditor' => [
	'filebrowserBrowseUrl' 		=> url('elfinder/ckeditor'),
	'filebrowserImageBrowseUrl' => url('elfinder/ckeditor')
],
```
When I comment the path all working
[Found here](http://stackoverflow.com/questions/28576088/why-am-i-getting-this-error-with-laravel-php-catchable-fatal-error)

**Comment by noxify** [comment]
Hi,

do you have added the 

```
'Barryvdh\Elfinder\ElfinderServiceProvider'
```

to the `providers` in `config/app.php`?

With the implementation of  #14 this provider have to be loaded also.

See also: http://docs.pseudoagentur.de/soa_sentinel#file-modification

Todo for me:
* Add Upgrade Guide

**Comment by Froxz** [comment]
Yes I updated my ```config/app.php``` 
I I also had read this. having no clue why is happening.

**Comment by noxify** [comment]
I found the problem - Fixed with PR #46.
The problem was, that the helper functions were present in the config file.
This produce the error in the CLI. 

With this fix, we solved the problem based on this comment: https://github.com/laravel/framework/issues/7671#issuecomment-97073967

**Comment by bihlmaierh** [comment]
PR #46 

Feel free to test and closing.

**Comment by noxify** [comment]
Fixed
