### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#47]
Branch: Develop
If user, is not in Admin group (or any other related to admin), if type in url: domain.com/admin (or wat ever setted in config) 
To many redirects will be thrown by browser.

**Comment by noxify** [comment]
Hi,

I will check it tomorrow.

Thanks for reporting.

**Comment by noxify** [comment]
Did you try only to open `<your-domain>/admin` or did you try to open something like `<your-domain>/admin/<model>` ?

**Comment by Froxz** [comment]
@noxify 
Just tried, if you open ```domain.com/admin/model``` it redirects you to ```domain.com/admin``` and after throws an error.

**Comment by Froxz** [comment]
@noxify the problem is in: ```middleware/AdminAuthenticate.php```
some how: the code runs until the end, end the end line says ```return redirect()->route('admin.dashboard')->withErrors('Permission denied.');``` To ridericts again to dashboard, but dushboard is not available, that why the loop is running.

**Comment by noxify** [comment]
Hi @Froxz,

i will check this.

Thanks a lot.

**Comment by Froxz** [comment]
Sorry @noxify also, not for this issue, just a question, ckeditor upload is working in develop branch?
Because when I choose ''Browse Server" it shows me in modal dashboard index page.

**Comment by bihlmaierh** [comment]
I have a Bugfix for that

I merge in the next hour

Before that I will correct redirect error



Am 14. September 2015 09:48:45 schrieb Froxz <notifications@github.com>:

**Comment by Froxz** [comment]
@bihlmaierh Thank you.

**Comment by bihlmaierh** [comment]
Pull #49 is in testing.

Please stay tuned!

**Comment by noxify** [comment]
Based on my tests the error still exists.

STRS:

* Logged in as Admin
* via phpMyAdmin is changed the Role permissions
** First Test => Changed `superadmin` from `true` to `false`
*** Expected: Dashboard is visible => OK
** Second Test => Changed also `controlpanel` from `true` to `false`
*** Expected: Redirect to Login Page
*** Current: `ERR_TOO_MANY_REDIRECTS`

@bihlmaierh - please fix it in release/3.0.1 branch.

**Comment by bihlmaierh** [comment]
Fixed in Milestone 3.0.1

**Comment by noxify** [comment]
Tested successfully.

If the user has not the "superadmin" or "controlpanel" permission, he will be redirected to the login page.
