### ISSUE TITLE
Public Folder Cleanup

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#51]
Public Folder should by clean up.

* Remove unused libaries
* Optimize Structure

**Comment by bihlmaierh** [comment]
@noxify 

What do you think about using Laravel Elixier (http://laravel.com/docs/5.1/elixir)

Greetings

**Comment by noxify** [comment]
inside the package? is this possible?

**Comment by bihlmaierh** [comment]
We have 2 possibilities:

* We merge the package gulpfile into the normal gulpfile
* We make a second gulpfile within package and the user needs to ask the task into the application gulpfile. Exampe see http://macr.ae/article/splitting-gulpfile-multiple-files.html

**Comment by noxify** [comment]
Both means then:
* User have to use elixir
* User have to use gulp

I think we should implement elixir as a optional functionality, because not everyone is using this.

**Comment by bihlmaierh** [comment]
Another idea:

* We publish the compiled backend.css and backend.js
* For Customizing the user needs to have gulp

**Comment by bihlmaierh** [comment]
PR #90 make this.

Closed!
