### ISSUE TITLE
Elfinder package

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#52]
After ```composer update``` runed ```php artisan vendor:publish --force``` to update files and ```public/packages``` but ```public/packages/barryvdh/elfinder``` are not publishing, had to to run ```php artisan elfinder:publish``` to publish assets. Maybe this is how it should be)) just asking)))

**Comment by noxify** [comment]
i will check this.

**Comment by noxify** [comment]
elfinder has their own command to publish the assets. So "yes" it works as designed :)
I will add it to the upgrade guide.

Thanks.

**Comment by noxify** [comment]
Added missing commands to the upgrade guide
https://github.com/Pseudoagentur/docs.pseudoagentur.de/blob/release/3.0.1/resources/docs/soa_sentinel/setup/upgrade.md
