### ISSUE TITLE
Test Results for 3.0.1 Test

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#53]
# Test Package

I used a fresh laravel installation for this test.

Dummy Table + Seeds are based on https://github.com/sleeping-owl/admin-3-demo

Link to Repository: https://github.com/Pseudoagentur/soa-testing

# Test Results

- Data Display Types (Tested also the functionality of each type e.g. filter, reorder, search etc.)
  - Table => OK
  - Datatables => OK
  - Datatables Async => OK
  - Tabs => OK
  - Tree => OK
  - Custom => OK 

- Data Filters
  - Scope => OK
  - Field => OK
  - Related => OK
  - Custom => OK

- Columns
  - Relations (count / lists ) => OK
  - Custom Columns => OK
  - Image => OK
  - Actions => OK

- Features
  - Orderable => OK
  - Column Filter (Datatables) => OK
  - Soft Delete + Restore => OK
  - Disable Create => OK
  - Disable Edit => OK
  - Disable Delete => OK

- Forms
  - Columns => OK 
  - Tabbed Form => OK
  - Show Form from Related Model => OK
  - Display List from Related Model + Redirect after creating a new record in the related Model => OK
  - Date Picker => OK
  - Time Picker => OK
  - Date/Time Picker => OK
  - Single File Upload + Preview + Delete => OK
  - Multi File Upload + Preview + Delete => OK
  - Textarea => OK
  - Text Field => OK
  - Text Addon => OK
  - Checkbox => OK
  - ckEditor => OK
  - elFinder => NOK 
  - Custom Field (from View) => OK
  - Simple Select => OK
  - TinyMCE - Default Settings (Missing Documentation to test more) => OK
  - Radio - Array + Enum + Model => OK
  - Bootstrap Select - Array + Model => OK
  - Bootstrap Select2 - Array + Model => OK
  - Choosen - Array + Model => OK
  - MultiSelect - Array + Model => OK

# Known Issues

## Action Button

The Action Button is not shown correctly in case that you're use it as global button in the display definition.

Something like this:

```
$display = AdminDisplay::table();
	$display->actions([
		Column::action('export')->value('Export')->icon('fa-share')->target('_blank')->callback(function ($collection)
		{
			dd('You are trying to export:', $collection->toArray());
		}),
	]);
```

If you're use it inside the column definition, everything works fine.

TODO:
* Find a solution :)

## Bulk Actions
In the tests, I did not get the Collection of my selected records

TODO:
* Find a solution :)

## elFinder
After a fresh installation, we have to modify the elfinder config,
otherwise we will get an error like:

```
ReflectionException in Container.php line 736:
Class replace-this-with-your-middleware does not exist
```

TODO:
* Find a solution :)

## Documentation
We have to update the documentation to have running examples for each FormItem.

**Comment by noxify** [comment]
Basic Test with Translation was successful.

Test Models can be found in the soa-testing repository.

**Comment by noxify** [comment]
Ajax Validation failed - requires to add the Service Provider and Alias to `config/app.php`
see: https://github.com/proengsoft/laravel-jsvalidation/wiki/Installation#configure-laravel

**Comment by noxify** [comment]
After adding ServiceProvider, Alias and publishing the resources, the ajax validation works fine.

- Required Field filled => Field is shown with a green border => OK
- Required Field is not filled => Field is shown with a red border and the correct validation message

**Comment by noxify** [comment]
Validation for translatable fields is also working fine and shows the correct field labels in the validation message.

**Comment by noxify** [comment]
documentation updated

**Comment by Froxz** [comment]
:+1:
