### ISSUE TITLE
Caching - Performance enhancement?

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#58]
Currently there is a discussion about the performance of SleepingOwl Admin Package:

https://laracasts.com/discuss/channels/laravel/how-to-improve-performance-when-calling-same-view-multiple-times?page=1

And https://github.com/sleeping-owl/admin/issues/237

We should test it and discuss about a possible solution.

I like the idea to cache the views. Maybe it's also possible to use caching also for other parts.

What do you think?

**Comment by bihlmaierh** [comment]
I think that's a good idea to optimize the speed. Can u make a solution proposal ?

I use currently for my frontend L5 Repositories with Cache functionality.

I think this feature is some thing for milestone 3.0.3
