### ISSUE TITLE
Question: External URL

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#59]
It is possible, add to ```menu: external url```, so they will be without ```admin prefix```?

**Comment by noxify** [comment]
Something like this?

```
Admin::menu()->external('https://www.pseudoagentur.de')->target("_blank")->label('Awesome Web Agency');
```

**Comment by Froxz** [comment]
@noxify yes, or inside same domain, 
Admin::menu()->external(route('home'))->label('Home');

Basically, I thought about this because I'm using Barryvdh Translation manager, and I can't get it work inside the admin, so I thought at least put a link in dashboard.

**Comment by noxify** [comment]
Did you try:

```
Admin::menu()->url(route('home'))->label('Custom Route Link');
```

Because the `url()` option will check for `://. 
So it should work with this.

**Comment by Froxz** [comment]
@noxify yes thank this if working for my registred route, but with barryvdh translation manager not, because you define the route in config and is not named route, or I can't find it)))).

**Comment by noxify** [comment]
What if you register the routes in your `app/Http/routes.php` ? 

Based on the original code, here an (untested) example :)
https://github.com/barryvdh/laravel-translation-manager/blob/master/src/ManagerServiceProvider.php#L83

```
Route::group([
		'prefix' => config('translation-manager.route.prefix', ''), 
		'middleware' => config('translation-manager.route.middleware', ''),
		'namespace' => 'Barryvdh\TranslationManager'
	], function() {

	Route::get('view/{group}', 'Controller@getView');
	Route::get('/', 'Controller');
});
```

**Comment by Froxz** [comment]
@noxify 
```Invalid route action: [App\Http\Controllers\Barryvdh\TranslationManager\Controller]```
I thin I need to override RouteServiceProvider map() function

**Comment by noxify** [comment]
Change `'namespace' => 'Barryvdh\TranslationManager'` to `'namespace' => '\Barryvdh\TranslationManager'`

**Comment by Froxz** [comment]
@noxify Sorry I did not include it to my previous answer, I tried it also. Same error.

**Comment by noxify** [comment]
Maybe you have to load the TranslationManager ServiceProvider before the SOA ServiceProvider in your `config/app.php`. Then the routes should be available.

**Comment by Froxz** [comment]
@noxify I will try it thank you a lot for the help,
Also about [#45](https://github.com/Pseudoagentur/soa-sentinel/issues/45)
```if($instance->status){
   return Column::custom()
  }else{
   Column::action() 
}```
How can implement this?

**Comment by noxify** [comment]
Good question :) 

@bihlmaierh can you help @Froxz with this in #45 ? 

Thanks :) 

Can we close this?

**Comment by Froxz** [comment]
@noxify xaxa))))) very good question :+1:
