### ISSUE TITLE
File / Image Upload Field

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#6]
Add a new option `path()` which will be used to define a custom destination for file / image upload.

**Comment by bihlmaierh** [comment]
Integrate BlueImp.

**Comment by Jok3r11of** [comment]
Also it will be nice nice to keep names, if files does not exist with this name, if exist rename it.

**Comment by bihlmaierh** [comment]
@Jok3r11of,

I need to check this feature during the implementation.

Thanks for proposal!

**Comment by bihlmaierh** [comment]
@noxify 

What do you mean ?

**Comment by Jok3r11of** [comment]
@bihlmaierh And on choice 
if ->keep() it will try to keep name if not provided rename.

**Comment by bihlmaierh** [comment]
@Jok3r11of 

Currently I test the following possibilities:

* Filename is orginal filename
* if filename exists, the current time will attach at the end

I think this day I make a pull request for develop branch

**Comment by Jok3r11of** [comment]
@bihlmaierh brilliant, thank you a lot. I will wait for master branch

**Comment by bihlmaierh** [comment]
Hello,

@noxify needs to check my changes. I think he will do this next week.

Addional I build in a delete function. So when u change your image or press "Delete File" the file is deleted on disk

**Comment by Jok3r11of** [comment]
@bihlmaierh This is good dont have to boot model on event trigger,
Also I wanted to ask option miltiple Model<->many<->AnotherModel attach() works, but when you save, it doesnt show the selected values.

**Comment by bihlmaierh** [comment]
What do u mean ?

**Comment by Jok3r11of** [comment]
@bihlmaierh 
```
FormItem::multiselect('categories', 'Categories')->model('App\MyModel')->display('title')
public function setCategoriesAttribute($categories)
{
    $this->categories()->detach();
    if ( ! $categories) return;
    if ( ! $this->exists) $this->save();

    $this->categories()->attach($categories);
}
```

After save it saveng correct, but on model preview  it doesn't shows already selected values.

**Comment by bihlmaierh** [comment]
Please make another issue with complete code.

**Comment by Jok3r11of** [comment]
@bihlmaierh  ok thank you

**Comment by bihlmaierh** [comment]
@Jok3r11of 

Have a look at pull request #38

**Comment by bihlmaierh** [comment]
@noxify 

Please verify and merge.

**Comment by noxify** [comment]
Can't merge, because there are some conflicts.

**Comment by bihlmaierh** [comment]
Merge IT ;)
-mobil gesendet-

Mit freundlichen Grüßen

Heiko Bihlmaier



Am 1. September 2015 15:28:18 schrieb Marcus Reinhardt 
<notifications@github.com>:

**Comment by noxify** [comment]
merged - @bihlmaierh please test the develop branch that everything is working
