### ISSUE TITLE
Question: Locale

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#62]
I have a middleware, that determinates the locale setted by user:
```php
<?php
namespace App\Http\Middleware;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use Closure;
use App;
use Carbon\Carbon;
class Language {
 
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {

        if(Session::has('locale')){
            App::setLocale(Session::get('locale'));
        }
        Carbon::setLocale(App::getLocale());
        return $next($request);
    }
 
}
```
andd Kernel.php looks like this:
```php
protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
        \App\Http\Middleware\Language::class,
    ];
```
Everything is working except menu in ```admin``` is not translating and uses default Locale
Maybe I should something before ```Language Middleware``` ??

**Comment by noxify** [comment]
Is it not the same problem like: https://github.com/sleeping-owl/admin/issues/226 ?

**Comment by Froxz** [comment]
@noxify yes :)) sorry dint't noticed that.

**Comment by noxify** [comment]
No problem :)

If you found another solution to solve this, please create an PR :) 

Thanks

**Comment by Froxz** [comment]
Maybe you can add a prefix, for locale? Or a a dropdown with languages on top bar, that can be defined in ```config/admin.php``` as array.

**Comment by noxify** [comment]
```
Or a a dropdown with languages on top bar, that can be defined in config/admin.php as array.
```

That's should be possible quickly. On click we will change then the AppLocale based on that whats defined in sleeping-owl#226

Or do you have another idea / solution?

**Comment by noxify** [comment]
implemented.

**Comment by noxify** [comment]
Documentation:
* http://docs.pseudoagentur.de/soa-sentinel/develop/translation/menu
* http://docs.pseudoagentur.de/soa-sentinel/develop/translation/model

**Comment by noxify** [comment]
Updated configuration: http://docs.pseudoagentur.de/soa-sentinel/develop/configuration/general
