### ISSUE TITLE
Searchable Columns

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#63]
Do we need this feature?

See: https://github.com/sleeping-owl/admin/issues/112

**Comment by Froxz** [comment]
@dunno can't understand the question xD )))

**Comment by noxify** [comment]
sould we implement the functionality to define which columns are searchable (I think for datatables (async) only).

**Comment by Froxz** [comment]
@noxify Why not, but I'm more wating for Sentinel manipulation))))

**Comment by noxify** [comment]
Implemented.
Documentation updated.
