### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#65]
Currently, there is no working implementation to show flash messages.

We need to implement/fix it that flash messages are visible.

* Create Message
* Update Message
* Delete Message
* Validations

**Comment by bihlmaierh** [comment]
We should implement a message for access violation too.

I think about a `abort(500, 'no access')` implementation or a flash message.

**Comment by bihlmaierh** [comment]
Using of https://github.com/laracasts/flash shoud be pratical.

Build in functions for alerts and overlay message.

@noxify What you think ?

**Comment by noxify** [comment]
Jap

**Comment by bihlmaierh** [comment]
I do this @noxify ;)

**Comment by bihlmaierh** [comment]
Fix in #113 
Close.

**Comment by noxify** [comment]
Please update documentation repository

**Comment by noxify** [comment]
added
