### ISSUE TITLE
Field filemanager

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#67]
Based on [this](https://github.com/Pseudoagentur/soa-sentinel/issues/14#issuecomment-135301651) @bihlmaierh noticed about ```FormItem::filemanager```` , do you think it is possible to add? An example if somebody want to add 10 the same images to different DB rows, in image field he will need to upload it 10 times. 

Also in config ```admin.php```
```php
/*
	 * Directory for file manager  (relative to public directory)
	 */
	'filemanagerDirectory' =>  'files/',
```
```/``` slush after ```files``` in DB columns files uploaded with ```files//path_to_file``` I think it should be removed, no?

**Comment by noxify** [comment]
We have implement a file manager currently only for ckeditor and for tinyMCE.

But yes, it's a good idea to implement it.
We will discuss this. I think with 3.0.3 we can implement it.

But if you want, you can create an PR with the solution.

**Comment by Froxz** [comment]
@noxify I need some explanations (In PM) in some fields and after I can try to implement something. Can I contact you email/Skype?

**Comment by noxify** [comment]
@Froxz sure.

Hangout / E-Mail: webstone@gmail.com

**Comment by bihlmaierh** [comment]
Hi @noxify ,

why we don't do this in Milestone 3.0.2 ? It's a very fast implemeting feature.

**Comment by noxify** [comment]
Added
