### ISSUE TITLE
Select-Field: Support for Scope & Different Seperators

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#69]
See Subject.

I will implement this tomorrow and so I can merge it into the next release

@noxify 
okay ?

**Comment by noxify** [comment]
Jop

**Comment by bihlmaierh** [comment]
Done with #81 

Todo: Check documenation.

**Comment by noxify** [comment]
@bihlmaierh - what's the status here?

**Comment by bihlmaierh** [comment]
Documentation is missing, I make this.

**Comment by noxify** [comment]
added docu: http://docs.pseudoagentur.de/soa-sentinel/develop/field/select
