### ISSUE TITLE
Documentation: Add Various Release Docs

### ISSUE THREAD

**Issue by bihlmaierh** [Pseudoagentur/soa-sentinel#70]
Example see laravel.org

When we do documentation after each new function we should have a multi version doc.

Can u implement this ?

**Comment by noxify** [comment]
Jap i will check it :)

**Comment by noxify** [comment]
First preview: http://docit.pseudoagentur.de/

I will use: https://github.com/docit/docit for this.
Sync will be done via a sync command: https://gist.github.com/noxify/e35edf67dc3719f6296b

Todo:
[ ] Create new Repository for admin-bridge
[ ] Modify doc structure
[ ] Update theme

**Comment by bihlmaierh** [comment]
Please fix version switch. There is an error :)

**Comment by noxify** [comment]
See Todo "Modify doc structure" ;)

**Comment by noxify** [comment]
Theme is updated and some responsive problems are fixed.
Now we will start to upgrade the documentations.

**Comment by noxify** [comment]
Updated Documentation Page.
Now docit is the new version at: http://docs.pseudoagentur.de/

Documentation Repos are:
* SOA Sentinel: https://github.com/Pseudoagentur/soa-sentinel-docs
* Admin Bridge: https://github.com/Pseudoagentur/admin-bridge-docs

Based on some security reasons, i use a private repo to manage the application
