### ISSUE TITLE
Layout Problems within AdminLTE

### ISSUE THREAD

**Issue by bihlmaierh** [Pseudoagentur/soa-sentinel#71]
Fix layout problems AdminLTE:
- DataTables has scrollbar
- create and action button overlaps (see attachment)
![attach](https://cloud.githubusercontent.com/assets/10707232/9983018/3554081e-5ff0-11e5-935f-c15c9c951131.PNG)

**Comment by noxify** [comment]
* Scrollbar is fixed
* Action button overlaps also fixed with the new method `bulk()`
** Forgot to update the documentation

**Comment by bihlmaierh** [comment]
* Scrollbar: check
* Action button overlaps: do you change doc ?

@noxify close when doc ready!

**Comment by noxify** [comment]
Added bulk method to the documentation:

* http://docs.pseudoagentur.de/soa-sentinel/develop/display/general#bulk-actions
* http://docs.pseudoagentur.de/soa-sentinel/develop/display/columns#action
