### ISSUE TITLE
Select Field

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#8]
Add alternatives to existing Select Field implementation.

* The default html select is available with `Field::select()`.
* Choosen Select is available with `Field::choosen()`
* BS Select is available with `Field::bsselect()`
* BS Select 2 is available with `Field::bsselect2()`
* Multiselect field will be removed and is now available as option `->multi(true)`
* The existing functionality for the MultiSelect should still work

**Comment by bihlmaierh** [comment]
Extend `$model->display('title')` implementation.

* Using display function should work with multiple fields. 
Example: `->display('kdnr|kdname')->separator(' - ')`

**Comment by noxify** [comment]
We have some conflicts in this PR.

**Comment by bihlmaierh** [comment]
Merge it i have done this locally
-mobil gesendet-

Mit freundlichen Grüßen

Heiko Bihlmaier



Am 1. September 2015 15:27:46 schrieb Marcus Reinhardt 
<notifications@github.com>:

**Comment by noxify** [comment]
merged - @bihlmaierh please test the develop branch that everything is working
