### ISSUE TITLE
Optimize Integration of TinyMCE

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#82]
* Add config setting for enabling elfinder within tinymce. When it's true, the neccessary function will include and the elfinder extension will automatically added to tinymce config
* Define of global tinymce configuration within config file.

@noxify 

More ideas ?

**Comment by noxify** [comment]
@bihlmaierh - what's the status here?

**Comment by bihlmaierh** [comment]
Currenty It's not possible to make a global configuration easily.

So I move this to the next release.

**Comment by heikobihlmaier** [comment]
Done in Release 3.0.3
