### ISSUE TITLE
Admin Routes

### ISSUE THREAD

**Issue by Froxz** [Pseudoagentur/soa-sentinel#83]
If I create a route, ecxept named route ```admin.dashboard``` in 
```php
app/admin/routes.php
```
It always redirects me back to dashboard(no Access), I thnik there is a need to review Middleware\AdminAuthenticate.php

**Comment by bihlmaierh** [comment]
Hello @Froxz,

which name has your route ?

Greetings.

**Comment by Froxz** [comment]
currently I have them as ```elfindel.something```, but if I name as what I want they dont work.

**Comment by bihlmaierh** [comment]
Okay, I will check this.

**Comment by bihlmaierh** [comment]
I close this because I will fix this in #89.
