### ISSUE TITLE
Bug: DataTables Sorting and Searching not working correctly

### ISSUE THREAD

**Issue by bihlmaierh** [Pseudoagentur/soa-sentinel#85]
Within the DataTables the sorting and search for custom fields or fields from relationsship doesn't work.

@noxify 

Can u look for this ?

**Comment by noxify** [comment]
Example?

**Comment by bihlmaierh** [comment]
http://laravel.io/bin/1yX9n

Searching and Sorting with "Kundennummer", "Kunde" and "Code" is not possible.

**Comment by bihlmaierh** [comment]
Currently this filtering and searching is not possible within ajax datatable. See here the doc.

So: I close this and mark as at invalid.
