### ISSUE TITLE
BackURL: Replacement for ID

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#86]
Since Release 3.0.1 we can define an individual backurl.

Here is a missing feature, because we can't redirect from a create to an edit form.

Reason for that is, that we can't replace a placeholder like `{id}` for the route.

I will add this feature.

**Comment by noxify** [comment]
@bihlmaierh - what's the status here?

**Comment by noxify** [comment]
Moved to 3.0.3

**Comment by heikobihlmaier** [comment]
closed, because #139
