### ISSUE TITLE
Custom Routes

### ISSUE THREAD

**Issue by heikobihlmaier** [Pseudoagentur/soa-sentinel#89]
add definition for custom routes to AdminMiddleware or add config params for custom routes to admin middleware.

This issue closing

#83 and #80

**Comment by bihlmaierh** [comment]
@noxify 

I have the following idea:

* within the configuration file of soa the user can define a new array with the name and the permission of route (permission is optional). So he can define custom routes with each name and each permission.

What do you mean ?

Greetings.

**Comment by bihlmaierh** [comment]
Fix in PR #113

**Comment by noxify** [comment]
Can you please also update the documentation branch?

**Comment by noxify** [comment]
updated config docu:
http://docs.pseudoagentur.de/soa-sentinel/develop/configuration/general
