### ISSUE TITLE
Date-Picker/DateTimePicker / Range-Picker

### ISSUE THREAD

**Issue by noxify** [Pseudoagentur/soa-sentinel#9]
Add new field or update existing `date` / `time` /  `timestamp` fields to enable functionality for http://www.eyecon.ro/bootstrap-datepicker/

**Comment by bihlmaierh** [comment]
Using buildin functionality of AdminLTE

**Comment by bihlmaierh** [comment]
Date-Picker/DateTimePicker is available soa default.

**Comment by bihlmaierh** [comment]
Can u do this ? :)

**Comment by noxify** [comment]
Currently we have already a good date/time picker implemented.
So we don't need to change something here currently.
